before_install:
    - sudo apt-get install openssh-server
    - sudo adduser --shell /bin/sh --disabled-password --gecos Frodo frodo
    - sudo adduser --shell /bin/sh --disabled-password --gecos Sam sam
    - sudo adduser --shell /bin/sh --disabled-password --gecos Gollum gollum

script:
    - status ssh
